safe_haven/main_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/signup/', views.signup, name='signup'),
    path('journals/new/', views.CreateJournal.as_view(), name='CreateJournal'),
    path('journals/all/', views.IndexJournal.as_view(), name='IndexJournal'),
    path('journals/<int:pk>/', views.DetailJournal.as_view(), name='Journal_detail'),
    path('journals/<int:pk>/update/', views.UpdateJournal.as_view(), name='Journal_update'),
    path('journals/<int:pk>/delete/', views.DeleteJournal.as_view(), name='Journal_delete'),

    path('articles/all', views.IndexArt.as_view(), name='IndexArt'),
    path('articles/new', views.CreateArt.as_view(), name='CreateArt'),
    path('articles/<int:pk>', views.DetailArt.as_view(), name='Art_detail'),
    path('articles/<int:pk>/update', views.UpdateArt.as_view(), name='Art_update'),
    path('articles/<int:pk>/delete', views.DeleteArt.as_view(), name='Art_delete'),

    path('moods/all/', views.IndexMood.as_view(), name='IndexMood'),
    path('moods/new/', views.AddMood.as_view(), name='AddMood'),
    path('moods/<int:pk>/', views.DetailMood.as_view(), name='Mood_detail'),
    path('moods/<int:pk>/update', views.UpdateMood.as_view(), name='mood_update'),
    path('moods/<int:pk>/delete', views.DeleteMood.as_view(), name='mood_delete'),

]

safe_haven/safe_haven/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

safe_haven/main_app/models.py
from django.db import models
from django.urls import reverse
from django.shortcuts import render
from django.contrib.auth.models import User
from datetime import date

# Create your models here.

IMPACT = (
    ("F", "Friends"),
    ("f", "Family"),
    ("S", "Studies"),
    ("R", "Relationship"),
    ("W", "Work"),
    ("H", "Health"),
    ("C", "Current Events"),
)

# ! change these

SCALE = (
    (1, "Very Low"),
    (2, "Low"),
    (3, "Medium"),
    (4, "High"),
    (5, "Very High"),
)


class Journal(models.Model):

    title = models.TextField()
    description = models.TextField()
    impact = models.CharField(max_length=1, choices=IMPACT)
    rate = models.IntegerField(choices=SCALE)
    date = models.DateField(default=date.today)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("Journal_detail", kwargs={"pk": self.pk})

class Article(models.Model):
    title = models.TextField()
    category = models.CharField(max_length=1)
    content = models.TextField()
    date = models.DateField(default=date.today)

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("Art_detail", kwargs={"pk": self.pk})

class Mood(models.Model):
    rate = models.IntegerField(choices=SCALE)
    reason = models.TextField()
    date = models.DateField(default=date.today)

    def __str__(self):
        return f"{self.rate} on {self.date}"

    def get_absolute_url(self):
        return reverse('home')

safe_haven/main_app/views.py
from django.shortcuts import render
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Journal, Article, Mood

# Create your views here.

def signup(request):
    err_msg = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid:
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            err_msg = 'Invalid signup - please try again'
    form = UserCreationForm()
    context = {'form': form, 'err_msg': err_msg}
    return render(request, 'registration/signup.html', context)

def home(request):
    articles = Article.objects.all()
    entries = Journal.objects.all()
    moods = Mood.objects.all()
    return render(request, 'home.html', {'articles': articles, 'entries': entries, 'moods': moods})

class IndexJournal(ListView):
    model = Journal
    #! change to .filter after applying auth
    entries = Journal.objects.all()
    context_object_name = 'entries'

class CreateJournal(CreateView):
    model = Journal
    fields = '__all__'

class DetailJournal(DetailView):
    model = Journal
    context_object_name = 'entry'

class UpdateJournal(UpdateView):
    model = Journal
    fields = '__all__'

class DeleteJournal(DeleteView):
    model = Journal
    success_url = '/journals/all'

class IndexArt(ListView):
    model = Article
    articles = Article.objects.all()
    context_object_name = 'articles'

class CreateArt(CreateView):
    model = Article
    fields = '__all__'

class UpdateArt(UpdateView):
    model = Article
    fields = '__all__'

class DetailArt(DetailView):
    model = Article
    context_object_name = 'article'

class DeleteArt(DeleteView):
    model = Article
    success_url = '/'

class IndexMood(ListView):
    model = Mood
    context_object_name = 'moods'

class AddMood(CreateView):
    model = Mood
    fields = '__all__'

class UpdateMood(UpdateView):
    model = Mood
    fields = '__all__'

class DetailMood(DetailView):
    model = Mood
    context_object_name = 'mood'

class DeleteMood(DeleteView):
    model = Mood
    success_url = '/'

safe_haven/main_app/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>Safe Haven</title>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav class="deep-purple accent-1">
        <div >
          <ul>
            <li><a href="{%url 'home' %}">SAFE HAVEN</a></li>
            <div class="right">

              <li><a href="{% url 'CreateJournal'%}">add entry</a></li>
              <li><a href="{% url 'AddMood'%}">Add mood</a></li>
              <!-- <li><a href="{% url 'IndexJournal'%}">All entries</a></li> -->
              <li><a href="{% url 'CreateArt'%}">Post an article</a></li>
            </div>
          </ul>
        </div>
      </nav>
    </header>
    <div class="container">{% block content %} {% endblock content %}</div>
  </body>
</html>

safe_haven/main_app/templates/home.html
{% extends "base.html" %}
{% block content %}

<h1>Home</h1>
<div class="divider"></div>
<!-- only for logged in users -->
{% include "./main_app/journal_list.html" %}
{% include "./main_app/mood_list.html" %}

<!-- for all -->
<div class="divider"></div>
{% include "./main_app/article_list.html" %}



{% endblock content %}

safe_haven/main_app/templates/main_app/article_confirm_delete.html
{% extends "./article_detail.html" %}
{% block confirm %}
<h5>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h5>
<form action="" method="POST">
  {% csrf_token %} <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'Journal_detail' object.id %}">Cancel</a>
</form>
{% endblock confirm %}

safe_haven/main_app/templates/main_app/article_detail.html
{% extends "base.html" %}
{% block content %}
{{article.title}}
{{article.content}}
<a href="{%url 'Art_update' object.id%}">Edit</a>
<a href="{%url 'Art_delete' object.id%}">Delete</a>
{%block confirm%}
{%endblock%}
{% endblock content %}

safe_haven/main_app/templates/main_app/article_form.html
{% extends "base.html" %}
{% block content %}
<form action="{%url 'CreateArt' %}" method="POST">
  {%csrf_token%}
  {{form.as_p}}
  <input type="submit" value="Post Article" class="btn blue">
</form>
{% endblock content %}

safe_haven/main_app/templates/main_app/article_list.html
<!-- get this to show in home.html & idk where else, using include -->
<div class="row">
<h2>Interesting Articles: </h2>
  {%for article in articles%}
  <div class="col">
    <a href="{%url 'Art_detail' article.id %}"><h1>{{article.title}}</h1></a>
  </div>
  {%endfor%}
</div>

safe_haven/main_app/templates/main_app/journal_confirm_delete.html
{% extends "./journal_detail.html" %}
{% block confirm %}
<h5>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h5>
<form action="" method="POST">
  {% csrf_token %} <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'Journal_detail' object.id %}">Cancel</a>
</form>
{% endblock confirm %}

safe_haven/main_app/templates/main_app/journal_detail.html
{% extends "base.html" %}
{% block content %}
<h1>{{entry.title}}</h1>
<a href="{%url 'Journal_update' object.id%}">Edit</a>
<a href="{%url 'Journal_delete' object.id%}">Delete</a>
{%block confirm%}
{%endblock%}

{% endblock content %}

safe_haven/main_app/templates/main_app/journal_form.html
{% extends "base.html" %}
{% block content %}
<form action="{%url 'CreateJournal'%}" method="POST">
  {%csrf_token%}
{{form.as_p}}
<input type="submit" value="Add Entry" class="btn">
</form>
<script>
    let selectEl = document.querySelectorAll('select')

  M.FormSelect.init(selectEl)

  var dateEl = document.getElementById("id_date")
  M.Datepicker.init(dateEl, {
    format: "yyyy-mm-dd",
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true,
  })

</script>
{% endblock content %}

safe_haven/main_app/templates/main_app/journal_list.html
{%for entry in entries %}
<a href="{%url 'Journal_detail' entry.id%}"><h5>{{entry.title}}</h5></a>
{%endfor%}

safe_haven/main_app/templates/main_app/mood_confirm_delete.html
{% extends "./mood_detail.html" %}
{% block confirm %}
<h5>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h5>
<form action="" method="POST">
  {% csrf_token %} <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'Journal_detail' object.id %}">Cancel</a>
</form>
{% endblock confirm %}

safe_haven/main_app/templates/main_app/mood_detail.html
{% extends "base.html" %}
{% block content %}
<h1>{{mood.rate}} because {{mood.reason}}</h1>
<a href="{%url 'mood_update' object.id%}">Edit</a>
<a href="{%url 'mood_delete' object.id%}">Delete</a>
{%block confirm%}
{%endblock%}
{% endblock content %}

safe_haven/main_app/templates/main_app/mood_form.html
{% extends "base.html" %}
{% block content %}
<form action="{%url 'AddMood' %}" method="POST">
  {%csrf_token%}
  {{form.as_p}}
  <input type="submit" value="Register Mood" class="btn blue">
</form>
{% endblock content %}

safe_haven/main_app/templates/main_app/mood_list.html
<div>
  <canvas id="myChart"></canvas>
</div>

<html data-ratings="{{moods}}" id="moods"></html>

<script>
  const ctx = document.getElementById('myChart');
  let moods = document.getElementById('moods')
  console.log(moods.dataset.ratings)
  let ratings = moods.dataset.ratings

  const dates = ratings.match(/\d{4}-\d{2}-\d{2}/g)
  const ratingsArr = ratings.match(/Mood:\s*(\d+)/g).map(m => Number(m.match(/\d+/)[0]))
  console.log(ratingsArr)
  new Chart(ctx, {
    type: 'line',
    data: {
      labels: dates,
      datasets: [{
        label: '',
        data: ratingsArr,
        borderWidth: 1
      }]
    },
    options: {
      scales: {
        y: {
          beginAtZero: true
        }
      }
    }
  });
</script>